name: Build package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_entire_package:
    runs-on: windows-2019

    steps:
    - name: Clone sources
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      
    - name: Build Catalyst managed layer
      run: |
        cd Managed
        dotnet restore
        dotnet build -c Debug --no-restore
        cd ..

    - name: Setup Ninja
      uses: urkle/action-get-ninja@v1.0.0
      
    - name: Prepare MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Build Catalyst shim DLL
      run: |
        cmake -G "Ninja" -S Native -B Native_build
        cd Native_build
        ninja
        cd ..
    
    - name: Consolidate build artifacts
      run: |
        mkdir Artifact
        mkdir Artifact/Catalyst
        copy Native_build/winhttp.dll Artifact/winhttp.dll
        copy Managed/Catalyst/bin/Debug/net35/Catalyst*.dll Artifact/Catalyst/Catalyst.dll
        
    - name: Upload artifact package
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Catalyst-SNAPSHOT
        path: Artifact
        if-no-files-found: error
        retention-days: 30
