name: Build package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_shim_dll:
    runs-on: windows-2019

    steps:
    - name: Clone sources
      uses: actions/checkout@v3

    - name: Setup Ninja
      uses: urkle/action-get-ninja@v1.0.0
      
    - name: Prepare MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Build Catalyst shim DLL
      run: |
        cmake -G "Ninja" -S Native -B Native_build
        cd Native_build
        ninja
